## https://docs.netlify.com/routing/redirects/rewrites-proxies/
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/XBuild.data*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/octet-stream"
	
[[headers]]
  for = "/assets/XBuild.wasm*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/wasm"
	
[[headers]]                                                                      
  for = "/assets/XBuild.framework.*.br"
  [headers.values]
    Content-Encoding = "br"
    Content-Type = "application/javascript"