const byAddress = {}

const testAddress = '0xd8d4bdb89d64b7a2971dc987dd67f101fea6c7d8'

/*
0xd8d4bdb89d64b7a2971dc987dd67f101fea6c7d8 has gotchis 160 - 239
Copy their data from polygon mainnet
https://subgraph.satsuma-prod.com/aavegotchi/aavegotchi-core-matic/version/v1.4.5-dev/playground
{
  aavegotchis(where:{
    id_in: ["160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239"]
  }) {
    id
    name
    withSetsRarityScore
    kinship
    level
    experience
    withSetsNumericTraits
  }
}

data.aavegotchis.map(g => ({
    id: g.id - 0,
    onchainId: g.id,
    name: g.name,
    "svgFront": `/dev/gotchi_g${1 + (g.id - 0) % 10}_front.svg`,
    "svgBack": "/dev/gotchi_g1_back.svg",
    "svgLeft": "/dev/gotchi_g1_left.svg",
    "svgRight": "/dev/gotchi_g1_right.svg",
    brs: g.withSetsRarityScore - 0,
    kinship: g.kinship - 0,
    level: g.level - 0,
    xp: g.experience - 0,
    "nrg": g.withSetsNumericTraits[0],
    "agg": g.withSetsNumericTraits[1],
    "spk": g.withSetsNumericTraits[2],
    "brn": g.withSetsNumericTraits[3],
    "eys": g.withSetsNumericTraits[4],
    "eyc": g.withSetsNumericTraits[5],
    "availableSpecials":
    [
        { "id": 1 }
    ],
    "specialId": 1,
    "speed": 10,
    "health": 20,
    "accuracy": 30,
    "evade": 40,
    "physical": 50,
    "magic": 60,
    "armor": 70,
    "resist": 80,
    "crit": 2,
    "hauntId": 2,
    "collateralType": "Dai",
    "eyeShape": "UncommonLow1",
    "eyeColor": "Common",
    "wearableBody": 0,
    "wearableFace": 0,
    "wearableEyes": 0,
    "wearableHead": 0,
    "wearableHandLeft": 0,
    "wearableHandRight": 0,
    "wearablePet": 0
}))
*/
byAddress[testAddress] = [
    {
        "id": 162,
        "onchainId": "162",
        "name": "Washington",
        "svgFront": "/dev/gotchi_g3_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 553,
        "kinship": 1593,
        "level": 5,
        "xp": 1225,
        "nrg": 103,
        "agg": 87,
        "spk": 92,
        "brn": 83,
        "eys": 78,
        "eyc": 5,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 163,
        "onchainId": "163",
        "name": "Lana Rhoades",
        "svgFront": "/dev/gotchi_g4_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 521,
        "kinship": 264,
        "level": 3,
        "xp": 445,
        "nrg": 71,
        "agg": 80,
        "spk": -4,
        "brn": 21,
        "eys": 91,
        "eyc": 85,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 164,
        "onchainId": "164",
        "name": "",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 468,
        "kinship": 1693,
        "level": 6,
        "xp": 1625,
        "nrg": 43,
        "agg": 0,
        "spk": 9,
        "brn": 98,
        "eys": 58,
        "eyc": 61,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 166,
        "onchainId": "166",
        "name": "el dollaro",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 491,
        "kinship": 1056,
        "level": 3,
        "xp": 350,
        "nrg": 31,
        "agg": 12,
        "spk": 6,
        "brn": 52,
        "eys": 99,
        "eyc": 86,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 167,
        "onchainId": "167",
        "name": "low id, 1200 kin",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 493,
        "kinship": 1424,
        "level": 4,
        "xp": 600,
        "nrg": 71,
        "agg": 1,
        "spk": 83,
        "brn": 91,
        "eys": 88,
        "eyc": 43,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 168,
        "onchainId": "168",
        "name": "vuk",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 624,
        "kinship": 3,
        "level": 2,
        "xp": 60,
        "nrg": 2,
        "agg": 106,
        "spk": 99,
        "brn": 23,
        "eys": 96,
        "eyc": 5,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 169,
        "onchainId": "169",
        "name": "S",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 460,
        "kinship": 1725,
        "level": 7,
        "xp": 2235,
        "nrg": 82,
        "agg": 31,
        "spk": 37,
        "brn": 70,
        "eys": 73,
        "eyc": 99,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 171,
        "onchainId": "171",
        "name": "kelly",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 467,
        "kinship": 50,
        "level": 1,
        "xp": 0,
        "nrg": 68,
        "agg": 64,
        "spk": 92,
        "brn": 81,
        "eys": 92,
        "eyc": 64,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 172,
        "onchainId": "172",
        "name": "QU33RGOTCHI",
        "svgFront": "/dev/gotchi_g3_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 740,
        "kinship": 42,
        "level": 13,
        "xp": 7535,
        "nrg": 94,
        "agg": 102,
        "spk": -19,
        "brn": 90,
        "eys": 2,
        "eyc": 88,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 174,
        "onchainId": "174",
        "name": "",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 493,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 58,
        "agg": 45,
        "spk": 1,
        "brn": 4,
        "eys": 88,
        "eyc": 94,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 181,
        "onchainId": "181",
        "name": "Weeboo",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 696,
        "kinship": 970,
        "level": 4,
        "xp": 790,
        "nrg": 102,
        "agg": 107,
        "spk": -6,
        "brn": 7,
        "eys": 0,
        "eyc": 20,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 183,
        "onchainId": "183",
        "name": "Spyro",
        "svgFront": "/dev/gotchi_g4_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 547,
        "kinship": 1607,
        "level": 7,
        "xp": 2420,
        "nrg": 52,
        "agg": 105,
        "spk": 103,
        "brn": 102,
        "eys": 6,
        "eyc": 70,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 185,
        "onchainId": "185",
        "name": "Crillon",
        "svgFront": "/dev/gotchi_g6_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 569,
        "kinship": 1629,
        "level": 6,
        "xp": 1656,
        "nrg": 98,
        "agg": 109,
        "spk": 98,
        "brn": 83,
        "eys": 92,
        "eyc": 66,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 186,
        "onchainId": "186",
        "name": "Fiat126",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 519,
        "kinship": 1660,
        "level": 7,
        "xp": 2060,
        "nrg": 96,
        "agg": 68,
        "spk": 68,
        "brn": 8,
        "eys": 97,
        "eyc": 93,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 187,
        "onchainId": "187",
        "name": "eshaal",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 457,
        "kinship": 886,
        "level": 3,
        "xp": 250,
        "nrg": 74,
        "agg": 82,
        "spk": 51,
        "brn": 32,
        "eys": 90,
        "eyc": 13,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 188,
        "onchainId": "188",
        "name": "ALPHASAURUS REX",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 521,
        "kinship": 967,
        "level": 5,
        "xp": 930,
        "nrg": 100,
        "agg": 43,
        "spk": 2,
        "brn": 1,
        "eys": 74,
        "eyc": 89,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 189,
        "onchainId": "189",
        "name": "Bear Maarket",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 525,
        "kinship": 945,
        "level": 4,
        "xp": 670,
        "nrg": 97,
        "agg": 80,
        "spk": 64,
        "brn": 92,
        "eys": 97,
        "eyc": 10,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 190,
        "onchainId": "190",
        "name": "It's USDT",
        "svgFront": "/dev/gotchi_g1_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 542,
        "kinship": 91,
        "level": 4,
        "xp": 710,
        "nrg": 86,
        "agg": 17,
        "spk": 21,
        "brn": 9,
        "eys": 98,
        "eyc": 98,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 191,
        "onchainId": "191",
        "name": "Tulsa",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 525,
        "kinship": 900,
        "level": 5,
        "xp": 1190,
        "nrg": 101,
        "agg": 89,
        "spk": 3,
        "brn": 81,
        "eys": 52,
        "eyc": 97,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 192,
        "onchainId": "192",
        "name": "JUNKFOOD",
        "svgFront": "/dev/gotchi_g3_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 538,
        "kinship": 1132,
        "level": 7,
        "xp": 2370,
        "nrg": 70,
        "agg": 81,
        "spk": 106,
        "brn": 92,
        "eys": 95,
        "eyc": 17,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 194,
        "onchainId": "194",
        "name": "",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 490,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 76,
        "agg": 83,
        "spk": 39,
        "brn": 92,
        "eys": 78,
        "eyc": 4,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 196,
        "onchainId": "196",
        "name": "AXS",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 480,
        "kinship": 230,
        "level": 2,
        "xp": 180,
        "nrg": 54,
        "agg": 80,
        "spk": 10,
        "brn": 90,
        "eys": 20,
        "eyc": 81,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 197,
        "onchainId": "197",
        "name": "Peter Eggplant Schiff",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 523,
        "kinship": 0,
        "level": 2,
        "xp": 60,
        "nrg": 33,
        "agg": 75,
        "spk": 96,
        "brn": 3,
        "eys": 91,
        "eyc": 93,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 198,
        "onchainId": "198",
        "name": "100x Chad",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 529,
        "kinship": 0,
        "level": 2,
        "xp": 60,
        "nrg": 67,
        "agg": 88,
        "spk": 23,
        "brn": 96,
        "eys": 97,
        "eyc": 99,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 199,
        "onchainId": "199",
        "name": "Defiant",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 519,
        "kinship": 941,
        "level": 4,
        "xp": 700,
        "nrg": 105,
        "agg": 65,
        "spk": 37,
        "brn": 85,
        "eys": 97,
        "eyc": 25,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 201,
        "onchainId": "201",
        "name": "VIDRUT",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 550,
        "kinship": 1721,
        "level": 8,
        "xp": 2490,
        "nrg": -2,
        "agg": 20,
        "spk": 85,
        "brn": -3,
        "eys": 6,
        "eyc": 73,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 202,
        "onchainId": "202",
        "name": "orbit",
        "svgFront": "/dev/gotchi_g3_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 503,
        "kinship": 844,
        "level": 3,
        "xp": 445,
        "nrg": 87,
        "agg": 49,
        "spk": 83,
        "brn": 3,
        "eys": 79,
        "eyc": 99,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 203,
        "onchainId": "203",
        "name": "",
        "svgFront": "/dev/gotchi_g4_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 499,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 73,
        "agg": 88,
        "spk": 94,
        "brn": 90,
        "eys": 96,
        "eyc": 52,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 204,
        "onchainId": "204",
        "name": "** MYTHICAL SPOOKINESS **",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 518,
        "kinship": 191,
        "level": 3,
        "xp": 280,
        "nrg": 19,
        "agg": 99,
        "spk": 104,
        "brn": 4,
        "eys": 44,
        "eyc": 70,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 205,
        "onchainId": "205",
        "name": "Jaason",
        "svgFront": "/dev/gotchi_g6_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 516,
        "kinship": 1319,
        "level": 5,
        "xp": 1090,
        "nrg": 81,
        "agg": 101,
        "spk": 68,
        "brn": 79,
        "eys": 89,
        "eyc": 92,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 206,
        "onchainId": "206",
        "name": "DAIamond Hands",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 534,
        "kinship": 1257,
        "level": 4,
        "xp": 750,
        "nrg": 103,
        "agg": 99,
        "spk": 98,
        "brn": 54,
        "eys": 86,
        "eyc": 25,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 207,
        "onchainId": "207",
        "name": "@cz",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 558,
        "kinship": 683,
        "level": 7,
        "xp": 1830,
        "nrg": 56,
        "agg": -6,
        "spk": -2,
        "brn": 84,
        "eys": 95,
        "eyc": 95,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 208,
        "onchainId": "208",
        "name": "krum",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 498,
        "kinship": 1127,
        "level": 5,
        "xp": 870,
        "nrg": 101,
        "agg": 16,
        "spk": 61,
        "brn": 54,
        "eys": 1,
        "eyc": 5,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 210,
        "onchainId": "210",
        "name": "gringotts",
        "svgFront": "/dev/gotchi_g1_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 526,
        "kinship": 942,
        "level": 3,
        "xp": 245,
        "nrg": -4,
        "agg": 5,
        "spk": 70,
        "brn": 66,
        "eys": 87,
        "eyc": 94,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 217,
        "onchainId": "217",
        "name": "M",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 442,
        "kinship": 20,
        "level": 1,
        "xp": 20,
        "nrg": 49,
        "agg": 77,
        "spk": 75,
        "brn": 89,
        "eys": 85,
        "eyc": 39,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 218,
        "onchainId": "218",
        "name": "LOVE MYTH 218 ID",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 509,
        "kinship": 1140,
        "level": 6,
        "xp": 1440,
        "nrg": 75,
        "agg": 91,
        "spk": 6,
        "brn": 16,
        "eys": 62,
        "eyc": 99,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 219,
        "onchainId": "219",
        "name": "GFA - Gentleman Farmer",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 540,
        "kinship": 1277,
        "level": 6,
        "xp": 1550,
        "nrg": 70,
        "agg": 91,
        "spk": 102,
        "brn": 2,
        "eys": 90,
        "eyc": 73,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 220,
        "onchainId": "220",
        "name": "",
        "svgFront": "/dev/gotchi_g1_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 508,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 76,
        "agg": 61,
        "spk": -5,
        "brn": 77,
        "eys": 89,
        "eyc": 4,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 221,
        "onchainId": "221",
        "name": "Miss Saigon",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 688,
        "kinship": 1520,
        "level": 6,
        "xp": 1630,
        "nrg": 3,
        "agg": 102,
        "spk": 2,
        "brn": 20,
        "eys": 92,
        "eyc": 91,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 224,
        "onchainId": "224",
        "name": "white lady",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 514,
        "kinship": 51,
        "level": 1,
        "xp": 0,
        "nrg": 98,
        "agg": 3,
        "spk": 88,
        "brn": 67,
        "eys": 91,
        "eyc": 31,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 225,
        "onchainId": "225",
        "name": "Tutti Frutti",
        "svgFront": "/dev/gotchi_g6_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 491,
        "kinship": 1770,
        "level": 7,
        "xp": 2405,
        "nrg": 92,
        "agg": 56,
        "spk": 58,
        "brn": 11,
        "eys": 99,
        "eyc": 7,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 226,
        "onchainId": "226",
        "name": "Momo #10",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 509,
        "kinship": 1556,
        "level": 6,
        "xp": 1370,
        "nrg": 93,
        "agg": 85,
        "spk": 55,
        "brn": 101,
        "eys": 91,
        "eyc": 78,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 227,
        "onchainId": "227",
        "name": "(T)_(T)",
        "svgFront": "/dev/gotchi_g8_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 473,
        "kinship": 863,
        "level": 3,
        "xp": 420,
        "nrg": 84,
        "agg": 43,
        "spk": 81,
        "brn": 45,
        "eys": 98,
        "eyc": 94,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 228,
        "onchainId": "228",
        "name": "228",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 539,
        "kinship": 674,
        "level": 2,
        "xp": 155,
        "nrg": 78,
        "agg": 91,
        "spk": 97,
        "brn": 77,
        "eys": 5,
        "eyc": 88,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 229,
        "onchainId": "229",
        "name": "prime minister",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 547,
        "kinship": 787,
        "level": 2,
        "xp": 130,
        "nrg": 98,
        "agg": 89,
        "spk": 29,
        "brn": 89,
        "eys": 10,
        "eyc": 96,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 230,
        "onchainId": "230",
        "name": "",
        "svgFront": "/dev/gotchi_g1_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 514,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 98,
        "agg": 18,
        "spk": 100,
        "brn": 87,
        "eys": 82,
        "eyc": 60,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 231,
        "onchainId": "231",
        "name": "Lead",
        "svgFront": "/dev/gotchi_g2_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 516,
        "kinship": 1408,
        "level": 3,
        "xp": 390,
        "nrg": 8,
        "agg": 73,
        "spk": 36,
        "brn": 1,
        "eys": 96,
        "eyc": 89,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 232,
        "onchainId": "232",
        "name": "",
        "svgFront": "/dev/gotchi_g3_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 484,
        "kinship": 0,
        "level": 0,
        "xp": 0,
        "nrg": 95,
        "agg": 100,
        "spk": 67,
        "brn": 88,
        "eys": 29,
        "eyc": 58,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 233,
        "onchainId": "233",
        "name": "Drop It Like It's Hot",
        "svgFront": "/dev/gotchi_g4_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 682,
        "kinship": 1685,
        "level": 8,
        "xp": 2839,
        "nrg": 8,
        "agg": 98,
        "spk": -3,
        "brn": 96,
        "eys": 94,
        "eyc": 91,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 234,
        "onchainId": "234",
        "name": "I believe",
        "svgFront": "/dev/gotchi_g5_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 562,
        "kinship": 1113,
        "level": 4,
        "xp": 750,
        "nrg": 96,
        "agg": 81,
        "spk": 85,
        "brn": 79,
        "eys": 92,
        "eyc": 5,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 235,
        "onchainId": "235",
        "name": "Sunny",
        "svgFront": "/dev/gotchi_g6_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 534,
        "kinship": 44,
        "level": 1,
        "xp": 40,
        "nrg": -1,
        "agg": 97,
        "spk": 20,
        "brn": 90,
        "eys": 88,
        "eyc": 69,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 236,
        "onchainId": "236",
        "name": "Terry",
        "svgFront": "/dev/gotchi_g7_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 708,
        "kinship": 1764,
        "level": 7,
        "xp": 2355,
        "nrg": 104,
        "agg": 98,
        "spk": 106,
        "brn": 104,
        "eys": 5,
        "eyc": 71,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 238,
        "onchainId": "238",
        "name": "Barry Chuckle RIP",
        "svgFront": "/dev/gotchi_g9_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 534,
        "kinship": 90,
        "level": 1,
        "xp": 20,
        "nrg": 84,
        "agg": 7,
        "spk": 75,
        "brn": 105,
        "eys": 82,
        "eyc": 86,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    },
    {
        "id": 239,
        "onchainId": "239",
        "name": "Summertime",
        "svgFront": "/dev/gotchi_g10_front.svg",
        "svgBack": "/dev/gotchi_g1_back.svg",
        "svgLeft": "/dev/gotchi_g1_left.svg",
        "svgRight": "/dev/gotchi_g1_right.svg",
        "brs": 473,
        "kinship": 1421,
        "level": 3,
        "xp": 240,
        "nrg": 28,
        "agg": 81,
        "spk": 93,
        "brn": 49,
        "eys": 92,
        "eyc": 19,
        "availableSpecials": [
            {
                "id": 1
            }
        ],
        "specialId": 1,
        "speed": 10,
        "health": 20,
        "accuracy": 30,
        "evade": 40,
        "physical": 50,
        "magic": 60,
        "armor": 70,
        "resist": 80,
        "crit": 2,
        "hauntId": 2,
        "collateralType": "Dai",
        "eyeShape": "UncommonLow1",
        "eyeColor": "Common",
        "wearableBody": 0,
        "wearableFace": 0,
        "wearableEyes": 0,
        "wearableHead": 0,
        "wearableHandLeft": 0,
        "wearableHandRight": 0,
        "wearablePet": 0
    }
]

export default byAddress